# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/proto/packet.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16src/proto/packet.proto\"X\n\x0eOutboundPacket\x12\x0c\n\x04\x64\x65st\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\r\n\x05\x64\x65sts\x18\x03 \x03(\t\x12\x18\n\x10max_holding_secs\x18\x04 \x01(\r\"-\n\rInboundPacket\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x62\x06proto3')
)




_OUTBOUNDPACKET = _descriptor.Descriptor(
  name='OutboundPacket',
  full_name='OutboundPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dest', full_name='OutboundPacket.dest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='OutboundPacket.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dests', full_name='OutboundPacket.dests', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_holding_secs', full_name='OutboundPacket.max_holding_secs', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=114,
)


_INBOUNDPACKET = _descriptor.Descriptor(
  name='InboundPacket',
  full_name='InboundPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='InboundPacket.src', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='InboundPacket.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['OutboundPacket'] = _OUTBOUNDPACKET
DESCRIPTOR.message_types_by_name['InboundPacket'] = _INBOUNDPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OutboundPacket = _reflection.GeneratedProtocolMessageType('OutboundPacket', (_message.Message,), dict(
  DESCRIPTOR = _OUTBOUNDPACKET,
  __module__ = 'src.proto.packet_pb2'
  # @@protoc_insertion_point(class_scope:OutboundPacket)
  ))
_sym_db.RegisterMessage(OutboundPacket)

InboundPacket = _reflection.GeneratedProtocolMessageType('InboundPacket', (_message.Message,), dict(
  DESCRIPTOR = _INBOUNDPACKET,
  __module__ = 'src.proto.packet_pb2'
  # @@protoc_insertion_point(class_scope:InboundPacket)
  ))
_sym_db.RegisterMessage(InboundPacket)


# @@protoc_insertion_point(module_scope)
